accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"

urlpatterns = [
    path("signup/", views.SignUpView.as_view(), name = "signup"),
]

pfyg/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView

urlpatterns = [
    path("accounts/", include("accounts.urls")),
    path("accounts/", include("django.contrib.auth.urls")),
    path("tasks/", include("tasks.urls")),
    path('admin/', admin.site.urls),
    path("", RedirectView.as_view(url="/tasks/"))
]

tasks/urls.py
from django.urls import path
from . import views

app_name = "tasks"

urlpatterns = [
    path("", views.index, name = "index"),
    path("new/", views.new, name = "new"),
    path("edit/<int:task_id>", views.edit, name = "edit"),
    path("delete/<int:task_id>", views.delete, name = "delete"),
    path("complete/<int:task_id>", views.complete, name = "complete"),
    path("reset/<int:task_id>", views.reset, name = "reset"),
    path("<str:option>", views.index, name = "index"),
]

accounts/models.py
from django.db import models

# Create your models here.

tasks/models.py
import base64
from datetime import date
from io import BytesIO

from django.contrib.auth.models import User
from django.db import models
from django.core import validators
from PIL import Image, ImageDraw, ImageFont


# Create your models here.
class Task(models.Model):
    taskName = models.CharField(max_length = 150, blank = False)
    taskImportance = models.IntegerField(default = 3,
                                         blank = False,
                                         validators = [
                                            validators.MinValueValidator(1),
                                            validators.MaxValueValidator(5)
                                            ])
    dueDate = models.DateField(blank = True, null = True)
    doneDate = models.DateField(blank = True, null = True)
    comment = models.CharField(max_length = 1024, blank = True, null = True)
    createDatetime = models.DateTimeField(auto_now_add=True)
    updateDatetime = models.DateTimeField(auto_now = True)
    completedDatetime = models.DateTimeField(blank = True, null = True)
    taskOwnerId = models.ForeignKey(User, on_delete=models.CASCADE, related_name = "tasks")

    def __str__(self):
        return self.taskName

    @classmethod
    def getTodaysCompletedTasks(cls):
        completedTasks = cls.objects.filter(\
            completedDatetime__date = date.today(),
            )
        return completedTasks

    @classmethod
    def getTaskGraph(cls, tasks):
        width = 800
        height = 400
        graph = Image.new("RGB", (width, height), (100,0,0))
        draw = ImageDraw.Draw(graph)
        font_size = 24 #文字の大きさの指定
        font = ImageFont.truetype('tasks/static/ume-hgo4.ttf', font_size)

        # tasks = Task.objects.filter(completedDatetime__isnull=True).order_by("dueDate").order_by("-taskImportance")
        tasks = tasks.order_by("dueDate").order_by("-taskImportance")
        # 下り順でソートして取得しているので、順番に上から並べれば重要度が高いものほど上に来る
        for i, task in enumerate(tasks):
            if task.dueDate is None:
                continue
            messageLength = len(task.taskName.encode("shift-jis"))
            yoko = width - (task.dueDate - date.today()).days * font_size * 3 # - font_size * messageLength / 2
            # if yoko >= width - len(task.taskName) * font_size:
            #     yoko = width - len(task.taskName) * font_size

            if yoko >= width - messageLength * font_size / 2:
                yoko = width - messageLength * font_size / 2
            if yoko < 10:
                yoko = 10

            draw.text((yoko-5 , i * 30 + 15), task.taskName, (255,255,255), font)

            if i >= 10:
                break

        buffer = BytesIO()
        graph.save(buffer, format="PNG")
        base64Img = base64.b64encode(buffer.getvalue()).decode().replace("'", "")
        return base64Img

tasks/forms.py
from django import forms

from .models import Task


class TaskForm(forms.ModelForm):

    class Meta:
        model = Task
        fields =("taskName", "taskImportance", "dueDate", "comment")

accounts/views.py
from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse_lazy
from django.views import generic


# Create your views here.

class SignUpView(generic.CreateView):
    form_class = UserCreationForm
    success_url = reverse_lazy("login")
    template_name = "accounts/signup.html"

tasks/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.utils import timezone
from django.contrib.auth.decorators import login_required

from .models import Task
from .forms import TaskForm

from django.contrib.auth.models import User

# Create your views here.

@login_required
def index(request, option = None):

    user_id = request.user.id
    user = User.objects.get(id=user_id)

    # tasks = Task.objects.filter(completedDatetime__isnull=True).order_by("dueDate")
    tasks = user.tasks.filter(completedDatetime__isnull=True).order_by("dueDate")
    if option:
        tasks = tasks.order_by(option)

    completedTasks = Task.getTodaysCompletedTasks()
    newform = TaskForm()
    forms = []
    for task in tasks:
        forms.append({"id": task.id, "form":TaskForm(instance = task)})

    taskGraphBase64 = Task.getTaskGraph(tasks)
    return render(request, "tasks/index.html", {"newform": newform, "forms": forms, "completedTasks": completedTasks, "taskGraphBase64": taskGraphBase64, "user": user})

@login_required
def new(request):
    form = TaskForm(request.POST)
    # form["taskOwnerId"] = request.user.id
    if form.is_valid():
        taskForm = form.save(commit = False)
        taskForm.taskOwnerId = request.user
        taskForm.save()

    return redirect("tasks:index")

@login_required
def edit(request, task_id):
    task = get_object_or_404(Task, id=task_id)
    if request.method == "POST":
        form = TaskForm(request.POST, instance = task)
        if form.is_valid():
            taskForm = form.save(commit = False)
            taskForm.taskOwnerId = request.user
            taskForm.save()
    return redirect("tasks:index")


@login_required
def delete(request, task_id):
    task = get_object_or_404(Task, id=task_id)
    if request.method == "POST" and task.taskOwnerId == request.user:
        task.delete()
    return redirect("tasks:index")


@login_required
def complete(request, task_id):
    task = get_object_or_404(Task, id=task_id)
    if request.method == "POST" and task.taskOwnerId == request.user:
        task.completedDatetime = timezone.datetime.now()
        task.save()

    return redirect("tasks:index")


@login_required
def reset(request, task_id):
    task = get_object_or_404(Task, id=task_id)
    if request.method == "POST":
        task.completedDatetime = None
        task.save()

    return redirect("tasks:index")

accounts/templates/accounts/signup.html
{% extends "base.html" %}

{% block content %}

<h1>Sign up</h1>
<section class="common-form">
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="submit">Sign up</button>
  </form>
</section>
{% endblock %}

tasks/templates/tasks/index.html
{% extends "base.html" %}

{% block content %}

  <p>{{ user.username }}さんこんにちは</p>

  <img src="data:image/png;base64,{{taskGraphBase64}}"/>

  <h2>タスク一覧</h2>
  <table class="table table-striped table-hover">
      <tr>
        <td  width="10%" align="center" valign="center">完了</td>
        <td align="center" valign="center"><a href="{% url "tasks:index" "-taskImportance" %}" class="btn btn-primary">重要度</a></td>
        <td align="center" valign="center">タスク名</td>
        <td align="center" valign="center"><a href ="{% url "tasks:index" %}" class="btn btn-primary">納期</a></td>
        <td align="center" valign="center">コメント</td>
        <td width="10%" align="center" valign="center">編集</td>
        <td width="10%" align="center" valign="center">削除</td>
      </tr>
      <tr>
        <td></td>
        <form action="{% url "tasks:new" %}" method="POST" >
          {% csrf_token %}
        <td>{{ newform.taskImportance }}</td>
        <td>{{ newform.taskName }}</td>
        <td>{{ newform.dueDate }}</td>
        <td>{{ newform.comment }}</td>
        <td colspan="2" align="center" valign="center"><button type="submit" class="btn btn-primary">新規登録</button></td>
      </form>
      </tr>


      {% for f in forms %}
      <tr>
        <td>
          <form action="{% url 'tasks:complete' f.id %}" method="POST">
            {% csrf_token %}
            <button type="submit" class="btn btn-primary">完了</button>
          </form>
        </td>
        <form action="{% url 'tasks:edit' f.id %}" method="POST">
          {% csrf_token %}
          <td>{{ f.form.taskImportance }}</td>
          <td>{{ f.form.taskName }}</td>
          <td>{{ f.form.dueDate }}</td>
          <td>{{ f.form.comment }}</td>
          <td><button type="submit" class="btn btn-primary">編集</button></td>
        </form>
        <td>
          <form action="{% url 'tasks:delete' f.id %}" method="POST">
            {% csrf_token %}
            <button type="submit" onclick='return confirm("本当に削除しますか？");'  class="btn btn-secondary">削除</button>
          </form>
        </td>
      </tr>
      {% endfor %}
  </table>

  <h2>きょう完了したタスク</h2>
  <table class="table table-striped table-hover">
    <tr>
      <td></td>
      <td>タスク名</td>
      <td>完了時間</td>
      <td>納期</td>
    </tr>
    {% for task in completedTasks %}
    <tr>
      <td><form action="{% url 'tasks:reset' task.id %}" method="POST">
        {% csrf_token %}
        <button type="submit" class="btn btn-secondary">未完了にする</button>
      </form></td>
      <td>{{ task.taskName }}</td>
      <td>{{ task.completedDatetime }}</td>
      <td>{{ task.dueDate }} </td>
    </tr>
    {% endfor %}
  </table>

{% endblock %}

templates/base.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>{% if request.path != '/' %}{% block title %}{% endblock %} | {% endif %}Blog App with Auth | Django2 Tutorial</title>
    <meta name='viewport' content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
</head>
<body>
<div class="container">
    <header>
        <p class="site-name"><a href="{% url 'tasks:index' %}">Blog App</a></p>
        <nav class='justify-content-start'>
            <ul>
                {% if user.is_authenticated %}
                <li><a href="{% url 'logout' %}" class="logout">Logout</a></li>
                {% else %}
                <li><a href="{% url 'login' %}" class="login">Login</a></li>
                <li><a href="{% url 'accounts:signup' %}" class="login">Sign Up</a></li>
                {% endif %}

            </ul>
        </nav>
    </header>
    <div class="container">
        {% block content %}{% endblock %}
    </div>
</div>
</body>
</html>